apiVersion: v1
kind: Namespace
metadata:
  name: fastapi
  labels:
    name: fastapi
    app.kubernetes.io/name: fastapi
    app.kubernetes.io/part-of: gardenos
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: fastapi-config
  namespace: fastapi
data:
  # Database connection (K3s PostgreSQL cluster)
  DATABASE_URL: "postgresql://postgres:postgres@postgres-cluster.postgres-cluster.svc.cluster.local:5432/postgres"
  
  # Supabase integration
  SUPABASE_URL: "http://postgrest.supabase.svc.cluster.local:3000"
  SUPABASE_AUTH_URL: "http://gotrue.supabase.svc.cluster.local:9999"
  
  # API Configuration
  API_V1_STR: "/api/v1"
  PROJECT_NAME: "GardenOS CRM API"
  
  # CORS
  BACKEND_CORS_ORIGINS: '["https://crm-jakenelwoods-projects.vercel.app", "http://localhost:3000"]'
  
  # Environment
  ENVIRONMENT: "production"
  
  # Logging
  LOG_LEVEL: "info"
---
apiVersion: v1
kind: Secret
metadata:
  name: fastapi-secrets
  namespace: fastapi
type: Opaque
stringData:
  # JWT Secret (should match Supabase)
  SECRET_KEY: "your-jwt-secret-key-here"
  
  # Supabase Service Role Key
  SUPABASE_SERVICE_ROLE_KEY: "your-service-role-key-here"
  
  # Database password
  DATABASE_PASSWORD: "your-secure-postgres-password"
  
  # RingCentral API credentials
  RINGCENTRAL_CLIENT_ID: "your-ringcentral-client-id"
  RINGCENTRAL_CLIENT_SECRET: "your-ringcentral-client-secret"
  RINGCENTRAL_SERVER_URL: "https://platform.ringcentral.com"
