export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[];

export interface Database {
  public: {
    Tables: {
      // =============================================================================
      // CORE TABLES
      // =============================================================================
      
      users: {
        Row: {
          id: string;
          email: string | null;
          full_name: string | null;
          avatar_url: string | null;
          role: string;
          phone_number: string | null;
          timezone: string;
          date_format: string;
          preferences: Json;
          is_active: boolean;
          last_login_at: string | null;
          metadata: Json;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id: string;
          email?: string | null;
          full_name?: string | null;
          avatar_url?: string | null;
          role?: string;
          phone_number?: string | null;
          timezone?: string;
          date_format?: string;
          preferences?: Json;
          is_active?: boolean;
          last_login_at?: string | null;
          metadata?: Json;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          email?: string | null;
          full_name?: string | null;
          avatar_url?: string | null;
          role?: string;
          phone_number?: string | null;
          timezone?: string;
          date_format?: string;
          preferences?: Json;
          is_active?: boolean;
          last_login_at?: string | null;
          metadata?: Json;
          created_at?: string;
          updated_at?: string;
        };
      };

      addresses: {
        Row: {
          id: string;
          street: string | null;
          street2: string | null;
          city: string | null;
          state: string | null;
          zip_code: string | null;
          country: string;
          type: string | null;
          is_verified: boolean;
          verification_source: string | null;
          verification_date: string | null;
          geocode_lat: number | null;
          geocode_lng: number | null;
          geocode_accuracy: string | null;
          geocode_source: string | null;
          geocode_date: string | null;
          formatted_address: string | null;
          plus_code: string | null;
          place_id: string | null;
          metadata: Json;
          notes: string | null;
          created_by: string | null;
          updated_by: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          street?: string | null;
          street2?: string | null;
          city?: string | null;
          state?: string | null;
          zip_code?: string | null;
          country?: string;
          type?: string | null;
          is_verified?: boolean;
          verification_source?: string | null;
          verification_date?: string | null;
          geocode_lat?: number | null;
          geocode_lng?: number | null;
          geocode_accuracy?: string | null;
          geocode_source?: string | null;
          geocode_date?: string | null;
          formatted_address?: string | null;
          plus_code?: string | null;
          place_id?: string | null;
          metadata?: Json;
          notes?: string | null;
          created_by?: string | null;
          updated_by?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          street?: string | null;
          street2?: string | null;
          city?: string | null;
          state?: string | null;
          zip_code?: string | null;
          country?: string;
          type?: string | null;
          is_verified?: boolean;
          verification_source?: string | null;
          verification_date?: string | null;
          geocode_lat?: number | null;
          geocode_lng?: number | null;
          geocode_accuracy?: string | null;
          geocode_source?: string | null;
          geocode_date?: string | null;
          formatted_address?: string | null;
          plus_code?: string | null;
          place_id?: string | null;
          metadata?: Json;
          notes?: string | null;
          created_by?: string | null;
          updated_by?: string | null;
          created_at?: string;
          updated_at?: string;
        };
      };

      clients: {
        Row: {
          id: string;
          client_type: string;
          name: string;
          email: string | null;
          phone_number: string | null;
          address_id: string | null;
          mailing_address_id: string | null;
          date_of_birth: string | null;
          gender: string | null;
          marital_status: string | null;
          drivers_license: string | null;
          license_state: string | null;
          education_occupation: string | null;
          referred_by: string | null;
          business_type: string | null;
          industry: string | null;
          tax_id: string | null;
          year_established: string | null;
          annual_revenue: number | null;
          number_of_employees: number | null;
          ai_summary: string | null;
          ai_next_action: string | null;
          ai_risk_score: number | null;
          ai_lifetime_value: number | null;
          ai_insights: Json;
          metadata: Json;
          tags: string[];
          status: string;
          source: string;
          created_by: string | null;
          updated_by: string | null;
          created_at: string;
          updated_at: string;
          last_contact_at: string | null;
          next_contact_at: string | null;
          converted_from_lead_id: string | null;
        };
        Insert: {
          id?: string;
          client_type: string;
          name: string;
          email?: string | null;
          phone_number?: string | null;
          address_id?: string | null;
          mailing_address_id?: string | null;
          date_of_birth?: string | null;
          gender?: string | null;
          marital_status?: string | null;
          drivers_license?: string | null;
          license_state?: string | null;
          education_occupation?: string | null;
          referred_by?: string | null;
          business_type?: string | null;
          industry?: string | null;
          tax_id?: string | null;
          year_established?: string | null;
          annual_revenue?: number | null;
          number_of_employees?: number | null;
          ai_summary?: string | null;
          ai_next_action?: string | null;
          ai_risk_score?: number | null;
          ai_lifetime_value?: number | null;
          ai_insights?: Json;
          metadata?: Json;
          tags?: string[];
          status?: string;
          source?: string;
          created_by?: string | null;
          updated_by?: string | null;
          created_at?: string;
          updated_at?: string;
          last_contact_at?: string | null;
          next_contact_at?: string | null;
          converted_from_lead_id?: string | null;
        };
        Update: {
          id?: string;
          client_type?: string;
          name?: string;
          email?: string | null;
          phone_number?: string | null;
          address_id?: string | null;
          mailing_address_id?: string | null;
          date_of_birth?: string | null;
          gender?: string | null;
          marital_status?: string | null;
          drivers_license?: string | null;
          license_state?: string | null;
          education_occupation?: string | null;
          referred_by?: string | null;
          business_type?: string | null;
          industry?: string | null;
          tax_id?: string | null;
          year_established?: string | null;
          annual_revenue?: number | null;
          number_of_employees?: number | null;
          ai_summary?: string | null;
          ai_next_action?: string | null;
          ai_risk_score?: number | null;
          ai_lifetime_value?: number | null;
          ai_insights?: Json;
          metadata?: Json;
          tags?: string[];
          status?: string;
          source?: string;
          created_by?: string | null;
          updated_by?: string | null;
          created_at?: string;
          updated_at?: string;
          last_contact_at?: string | null;
          next_contact_at?: string | null;
          converted_from_lead_id?: string | null;
        };
      };

      leads: {
        Row: {
          id: string;
          client_id: string | null;
          assigned_to: string | null;
          lead_type: string;
          priority: string;
          current_carrier: string | null;
          current_policy_expiry: string | null;
          premium: number | null;
          auto_premium: number | null;
          home_premium: number | null;
          specialty_premium: number | null;
          commercial_premium: number | null;
          auto_data: Json;
          auto_data_version: number;
          home_data: Json;
          home_data_version: number;
          specialty_data: Json;
          specialty_data_version: number;
          commercial_data: Json;
          commercial_data_version: number;
          liability_data: Json;
          liability_data_version: number;
          additional_insureds: Json;
          additional_locations: Json;
          drivers: Json;
          vehicles: Json;
          ai_summary: string | null;
          ai_next_action: string | null;
          ai_quote_recommendation: string | null;
          ai_follow_up_priority: number | null;
          ai_conversion_probability: number | null;
          ai_insights: Json;
          campaign_id: string | null;
          ab_test_id: string | null;
          content_template_id: string | null;
          attribution_data: Json;
          metadata: Json;
          tags: string[];
          notes: string | null;
          custom_fields: Json;
          source: string;
          import_file_name: string | null;
          import_batch_id: string | null;
          status: string;
          pipeline_id: number | null;
          pipeline_status_id: number | null;
          insurance_type_id: number | null;
          lead_status_id: number | null;
          created_by: string | null;
          updated_by: string | null;
          created_at: string;
          updated_at: string;
          status_changed_at: string;
          last_contact_at: string | null;
          next_contact_at: string | null;
          quote_generated_at: string | null;
          sold_at: string | null;
          lost_at: string | null;
          hibernated_at: string | null;
        };
        Insert: {
          id?: string;
          client_id?: string | null;
          assigned_to?: string | null;
          lead_type?: string;
          priority?: string;
          current_carrier?: string | null;
          current_policy_expiry?: string | null;
          premium?: number | null;
          auto_premium?: number | null;
          home_premium?: number | null;
          specialty_premium?: number | null;
          commercial_premium?: number | null;
          auto_data?: Json;
          auto_data_version?: number;
          home_data?: Json;
          home_data_version?: number;
          specialty_data?: Json;
          specialty_data_version?: number;
          commercial_data?: Json;
          commercial_data_version?: number;
          liability_data?: Json;
          liability_data_version?: number;
          additional_insureds?: Json;
          additional_locations?: Json;
          drivers?: Json;
          vehicles?: Json;
          ai_summary?: string | null;
          ai_next_action?: string | null;
          ai_quote_recommendation?: string | null;
          ai_follow_up_priority?: number | null;
          ai_conversion_probability?: number | null;
          ai_insights?: Json;
          campaign_id?: string | null;
          ab_test_id?: string | null;
          content_template_id?: string | null;
          attribution_data?: Json;
          metadata?: Json;
          tags?: string[];
          notes?: string | null;
          custom_fields?: Json;
          source?: string;
          import_file_name?: string | null;
          import_batch_id?: string | null;
          status?: string;
          pipeline_id?: number | null;
          pipeline_status_id?: number | null;
          insurance_type_id?: number | null;
          lead_status_id?: number | null;
          created_by?: string | null;
          updated_by?: string | null;
          created_at?: string;
          updated_at?: string;
          status_changed_at?: string;
          last_contact_at?: string | null;
          next_contact_at?: string | null;
          quote_generated_at?: string | null;
          sold_at?: string | null;
          lost_at?: string | null;
          hibernated_at?: string | null;
        };
        Update: {
          id?: string;
          client_id?: string | null;
          assigned_to?: string | null;
          lead_type?: string;
          priority?: string;
          current_carrier?: string | null;
          current_policy_expiry?: string | null;
          premium?: number | null;
          auto_premium?: number | null;
          home_premium?: number | null;
          specialty_premium?: number | null;
          commercial_premium?: number | null;
          auto_data?: Json;
          auto_data_version?: number;
          home_data?: Json;
          home_data_version?: number;
          specialty_data?: Json;
          specialty_data_version?: number;
          commercial_data?: Json;
          commercial_data_version?: number;
          liability_data?: Json;
          liability_data_version?: number;
          additional_insureds?: Json;
          additional_locations?: Json;
          drivers?: Json;
          vehicles?: Json;
          ai_summary?: string | null;
          ai_next_action?: string | null;
          ai_quote_recommendation?: string | null;
          ai_follow_up_priority?: number | null;
          ai_conversion_probability?: number | null;
          ai_insights?: Json;
          campaign_id?: string | null;
          ab_test_id?: string | null;
          content_template_id?: string | null;
          attribution_data?: Json;
          metadata?: Json;
          tags?: string[];
          notes?: string | null;
          custom_fields?: Json;
          source?: string;
          import_file_name?: string | null;
          import_batch_id?: string | null;
          status?: string;
          pipeline_id?: number | null;
          pipeline_status_id?: number | null;
          insurance_type_id?: number | null;
          lead_status_id?: number | null;
          created_by?: string | null;
          updated_by?: string | null;
          created_at?: string;
          updated_at?: string;
          status_changed_at?: string;
          last_contact_at?: string | null;
          next_contact_at?: string | null;
          quote_generated_at?: string | null;
          sold_at?: string | null;
          lost_at?: string | null;
          hibernated_at?: string | null;
        };
      };
