apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgrest
  namespace: supabase
  labels:
    app: postgrest
    component: api
    app.kubernetes.io/name: postgrest
    app.kubernetes.io/part-of: supabase
spec:
  replicas: 2
  selector:
    matchLabels:
      app: postgrest
  template:
    metadata:
      labels:
        app: postgrest
        component: api
    spec:
      nodeSelector:
        node.gardenos.io/tier: hybrid
      containers:
      - name: postgrest
        image: postgrest/postgrest:v12.2.3
        ports:
        - containerPort: 3000
          name: http
        env:
        - name: PGRST_DB_URI
          value: "postgres://postgres:postgres@postgres-cluster.postgres-cluster.svc.cluster.local:5432/postgres?target_session_attrs=read-write"
        - name: PGRST_DB_SCHEMAS
          value: "public,storage,graphql_public"
        - name: PGRST_DB_ANON_ROLE
          value: "anon"
        - name: PGRST_JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: supabase-secrets
              key: JWT_SECRET
        - name: PGRST_DB_USE_LEGACY_GUCS
          value: "false"
        - name: PGRST_APP_SETTINGS_JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: supabase-secrets
              key: JWT_SECRET
        - name: PGRST_APP_SETTINGS_JWT_EXP
          valueFrom:
            configMapKeyRef:
              name: supabase-config
              key: JWT_EXPIRY
        envFrom:
        - configMapRef:
            name: supabase-config
        - secretRef:
            name: supabase-secrets
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"
        livenessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: postgrest
  namespace: supabase
  labels:
    app: postgrest
    component: api
spec:
  selector:
    app: postgrest
  ports:
  - port: 3000
    targetPort: 3000
    name: http
  type: ClusterIP
