apiVersion: v1
kind: Namespace
metadata:
  name: ingress-nginx
  labels:
    app.kubernetes.io/name: ingress-nginx
    app.kubernetes.io/part-of: gardenos
---
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: nginx-ingress
  namespace: kube-system
spec:
  chart: ingress-nginx
  repo: https://kubernetes.github.io/ingress-nginx
  targetNamespace: ingress-nginx
  valuesContent: |-
    controller:
      # Use host network for better performance
      hostNetwork: true
      hostPort:
        enabled: true
        ports:
          http: 80
          https: 443
      
      # Node selector for hybrid nodes
      nodeSelector:
        node.gardenos.io/tier: hybrid
      
      # Tolerations for control plane nodes
      tolerations:
      - key: node-role.kubernetes.io/control-plane
        operator: Exists
        effect: NoSchedule
      
      # Service configuration
      service:
        type: ClusterIP
        
      # Resource limits
      resources:
        requests:
          cpu: 100m
          memory: 90Mi
        limits:
          cpu: 200m
          memory: 180Mi
      
      # Configuration
      config:
        use-forwarded-headers: "true"
        compute-full-forwarded-for: "true"
        use-proxy-protocol: "false"
        
      # Metrics
      metrics:
        enabled: true
        serviceMonitor:
          enabled: false
      
      # Admission webhooks
      admissionWebhooks:
        enabled: false
    
    # Default backend
    defaultBackend:
      enabled: true
      nodeSelector:
        node.gardenos.io/tier: hybrid
      resources:
        requests:
          cpu: 10m
          memory: 20Mi
        limits:
          cpu: 20m
          memory: 40Mi
